### ISSUE TITLE
Add NEET

### ISSUE THREAD

**Issue by brishtibheja** [Raagaception/raagaception-12STD-CBSE-deck#10]
Hello there, I am preparing for NEET and there is a really good deck from u/fleecesnatcher

Can that be added here? Will be helpful for everyone. Also I can manage issues but PR, forking etcetera goes over my head so I won't be able to help.

**Comment by Raagaception** [comment]
Hi! Firstly, I profusely apologize for the extremely late reply. I was hung up with some real life commitments.

> there is a really good deck from u/fleecesnatcher

Yes, I'm aware of the u/fleecesnatcher deck, but since they haven't given permission for us to merge their cards into our project, I can't include that. We've got it linked in our "reccomended decks" sections on Discord though, which can be found [here](https://discord.com/channels/843357011948863500/843357893439782942/843369537705476096). If you aren't part of it, feel free to join using [our invite link](https://discord.gg/kbSXsRTUC2).

> Also I can manage issues but PR, forking etcetera goes over my head

Unfortunately, that holds true for most people. Even for me, keeping up with Anki and CrowdAnki feature updates has been impossible due to academic commitments. As of today, I'm officially ending support for this deck. My apologies. But, if you or someone else is up for it, you may fork this project and carry on the work on Github.

**Comment by brishtibheja** [comment]
That is sad to here. These decks are amazingly vast and extensive. I really appreciate the work that was done here. I expect others to modify and build upon this. A legacy has been left!

Actually, I didn't realise that these decks were not being supported anymore. I read the README and it is clear to me now. Life can certainly get busy for everyone. 
 I think if support is really being ended, perhaps it would make sense to archive the repo and make it read only. This will make it clearer for everyone what is happening as not everyone might read the README page. In any case, thanks for all the effort, you and everybody else! I hope NCERT doesn't take more weird decisions with our syllabus and people can continue to use the original Raagaception's.

**Comment by Raagaception** [comment]
> I think if support is really being ended, perhaps it would make sense to archive the repo and make it read only. This will make it clearer for everyone what is happening as not everyone might read the README page.

Great idea! Somehow I forgot about it. Will implement today. Hopefully archiving won't prevent others from forking the repo?
